# Generated by Django 4.2.6 on 2023-10-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.PositiveIntegerField(default=1698488052),
        ),
    ]
