# Generated by Django 4.2.6 on 2023-11-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_user_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.PositiveIntegerField(default=1699771880),
        ),
    ]
